In [56]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from tensorflow import keras
from tensorflow.keras import layers

In [57]:
dataset_train = pd.read_csv("Google_Stock_Price_Train.csv")
train_data = dataset_train['Open']
train_data.head()

Open
0  325.25
1  331.27
2  329.83
3  328.34
4  322.04

In [58]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
train_data = scaler.fit_transform(train_data)
train_data

array([[0.08581368],
       [0.09701243],
       [0.09433366],
       ...,
       [0.95725128],
       [0.93796041],
       [0.93688146]])

In [59]:
X_train = []
y_train = []
for i in range(60, 1258):
  X_train.append(train_data[i-60: i, 0])
  y_train.append(train_data[i, 0])
X_train = np.array(X_train)
y_train = np.array(y_train)
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
X_train

array([[[0.08581368],
        [0.09701243],
        [0.09433366],
        ...,
        [0.07846566],
        [0.08034452],
        [0.08497656]],

       [[0.09701243],
        [0.09433366],
        [0.09156187],
        ...,
        [0.08034452],
        [0.08497656],
        [0.08627874]],

       [[0.09433366],
        [0.09156187],
        [0.07984225],
        ...,
        [0.08497656],
        [0.08627874],
        [0.08471612]],

       ...,

       [[0.92106928],
        [0.92438053],
        [0.93048218],
        ...,
        [0.95475854],
        [0.95204256],
        [0.95163331]],

       [[0.92438053],
        [0.93048218],
        [0.9299055 ],
        ...,
        [0.95204256],
        [0.95163331],
        [0.95725128]],

       [[0.93048218],
        [0.9299055 ],
        [0.93113327],
        ...,
        [0.95163331],
        [0.95725128],
        [0.93796041]]])

In [60]:
model = keras.Sequential()
model.add(layers.LSTM(units=50, return_sequences=True, input_shape=(X_train.shape[1], X_train.shape[2])))
model.add(layers.Dropout(0.2))
model.add(layers.LSTM(units=50, return_sequences=True))
model.add(layers.Dropout(0.2))
model.add(layers.LSTM(units=50, return_sequences=True))
model.add(layers.Dropout(0.2))
model.add(layers.LSTM(units=50))
model.add(layers.Dropout(0.2))
model.add(layers.Dense(1))

In [61]:
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(X_train, y_train, epochs=100, batch_size=32)

Epoch 1/100


38/38 [==============================] - 13s 86ms/step - loss: 0.0421
Epoch 2/100
38/38 [==============================] - 3s 87ms/step - loss: 0.0072
Epoch 3/100
38/38 [==============================] - 4s 95ms/step - loss: 0.0059
Epoch 4/100
38/38 [==============================] - 4s 108ms/step - loss: 0.0061
Epoch 5/100
38/38 [==============================] - 4s 102ms/step - loss: 0.0054
Epoch 6/100
38/38 [==============================] - 4s 100ms/step - loss: 0.0053
Epoch 7/100
38/38 [==============================] - 4s 100ms/step - loss: 0.0047
Epoch 8/100
38/38 [==============================] - 4s 109ms/step - loss: 0.0046
Epoch 9/100
38/38 [==============================] - 4s 98ms/step - loss: 0.0047
Epoch 10/100
38/38 [==============================] - 4s 97ms/step - loss: 0.0046
Epoch 11/100
38/38 [==============================] - 4s 109ms/step - loss: 0.0045
Epoch 12/100
38/38 [==============================] - 4s 95ms/step - loss: 0.0041
Epoch 13/100
38/38 [==========

In [65]:
dataset_test = pd.read_csv('Google_Stock_Price_Test.csv')
test_data = dataset_train['Open'].values

array([325.25, 331.27, 329.83, ..., 793.7 , 783.33, 782.75])